# Generated by Django 4.2 on 2023-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
