# Generated by Django 4.2 on 2023-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.TextField(default='', max_length=255),
        ),
    ]
