# Generated by Django 4.2 on 2023-05-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_choice_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
