# Generated by Django 4.2 on 2023-05-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_poll_pollchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='pollchoice',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollChoice',
        ),
    ]
