# Generated by Django 4.2 on 2023-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
